### ISSUE TITLE
topgrade panics with the --dry-run flag when VS Code extension updates are enabled

### ISSUE THREAD

**Issue by SanchithHegde** [r-darwish/topgrade#632]
**What did you expect to happen?**
`topgrade` shouldn't panic when the `--dry-run` flag is passed and VS Code extension updates are enabled.

**What actually happened?**
`topgrade` panics when the `--dry-run` flag is passed and VS Code extension updates are enabled. I disabled VS Code extension updates and I no longer face the issue. Normal updates (just running `topgrade` without any flags) are unaffected by this issue.

**Additional details:**
- Which operating system or Linux distribution are you using? Arch Linux
- How did you install Topgrade? AUR package, `topgrade 6.5.1-1`

<details>
<summary>Output of <code>RUST_BACKTRACE=1 cargo r -- --dry-run --verbose --only vs_code</code></summary>

(Running with `cargo` for debug output.)

<pre>
❯ RUST_BACKTRACE=1 cargo r -- --dry-run --verbose --only vs_code            
   Compiling topgrade v6.5.1 (/home/username/Downloads/topgrade)
    Finished dev [unoptimized + debuginfo] target(s) in 1.61s
     Running `target/debug/topgrade --dry-run --verbose --only vs_code`
 2021-02-14T20:18:45.924Z DEBUG topgrade::config > Configuration at /home/username/.config/topgrade.toml
 2021-02-14T20:18:45.924Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, post_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: Some([Asdf, Gem]), ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, bashit_branch: None, only: None, composer: None, brew: None, linux: None, git: None, windows: None, vagrant: None }
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Detected "/usr/bin/notify-send" as "notify-send"
 2021-02-14T20:18:45.925Z DEBUG topgrade         > Version: 6.5.1
 2021-02-14T20:18:45.925Z DEBUG topgrade         > OS: x86_64-unknown-linux-gnu
 2021-02-14T20:18:45.925Z DEBUG topgrade         > Args { inner: ["target/debug/topgrade", "--dry-run", "--verbose", "--only", "vs_code"] }
 2021-02-14T20:18:45.925Z DEBUG topgrade         > Binary path: Ok("/home/username/Downloads/topgrade/target/debug/topgrade")
 2021-02-14T20:18:45.925Z DEBUG topgrade         > Self Update: false
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Detected "/usr/bin/git" as "git"
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Cannot find "doas"
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Detected "/usr/bin/sudo" as "sudo"
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Cannot find "powershell"
 2021-02-14T20:18:45.925Z DEBUG topgrade::utils  > Path "/home/username/.config/emacs" doesn't exist
 2021-02-14T20:18:45.926Z DEBUG topgrade::utils  > Path "/home/username/.emacs.d" doesn't exist
 2021-02-14T20:18:45.926Z DEBUG topgrade::steps::git > /home/username/.zsh/.zshrc is a file. Checking /home/username/.zsh
 2021-02-14T20:18:45.926Z DEBUG topgrade::steps::git > Checking if /home/username/.zsh is a git repository
 2021-02-14T20:18:45.927Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(32768)), stdout: "", stderr: "fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n" }
 2021-02-14T20:18:45.927Z DEBUG topgrade::steps::git > /home/username/.config/fish does not exists
 2021-02-14T20:18:45.927Z DEBUG topgrade::steps::git > /home/username/.config/openbox does not exists
 2021-02-14T20:18:45.927Z DEBUG topgrade::steps::git > /home/username/.config/bspwm does not exists
 2021-02-14T20:18:45.927Z DEBUG topgrade::steps::git > /home/username/.config/i3 does not exists
 2021-02-14T20:18:45.927Z DEBUG topgrade::steps::git > /home/username/.config/sway does not exists
 2021-02-14T20:18:45.927Z DEBUG topgrade::runner     > Step "vscode"
 2021-02-14T20:18:45.927Z DEBUG topgrade::utils      > Detected "/usr/bin/code" as "code"

―― 01:48:45 - Visual Studio Code ―――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/code --list-extensions
thread 'main' panicked at 'internal error: entered unreachable code', src/executor.rs:272:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: <topgrade::executor::Executor as topgrade::executor::CommandExt>::check_output
             at ./src/executor.rs:272:36
   4: topgrade::steps::generic::run_vscode
             at ./src/steps/generic.rs:89:19
   5: topgrade::run::{{closure}}
             at ./src/main.rs:280:47
   6: topgrade::runner::Runner::execute
             at ./src/runner.rs:37:19
   7: topgrade::run
             at ./src/main.rs:280:5
   8: topgrade::main
             at ./src/main.rs:427:11
   9: core::ops::function::FnOnce::call_once
             at /home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>
</details>

---

Also, when I was testing out, I found that the `--disable` and the `--only` flags expect `vs_code` as an argument, but the `[disable]` section in the TOML file expects `v_s_code`. Is that intended behavior?

**Comment by SanchithHegde** [comment]
@r-darwish Thank you for the quick fix!
