### ISSUE TITLE
Panic on cargo update

### ISSUE THREAD

**Issue by chrispickard** [r-darwish/topgrade#94]
This morning I ran topgrade on my CentOS 7.5.1804 machine.
rustup info:
```
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.32.0-nightly (13c943992 2018-11-18)
```
and got a panic from cargo update
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 9, message: "object not found - no match for id (71434897673bf701aa2a9a55f1ec5740b6122a0d)" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: cargo_update::ops::GitRepoPackage::pull_version
  10: cargo_install_update::actual_main
  11: cargo_install_update::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: <unknown>
```

**Comment by r-darwish** [comment]
I basically just run `cargo install-update --git --all`. Does this still happen if you run this command directly?

**Comment by chrispickard** [comment]
I reported this upstream in nabijaczleweli/cargo-update#99

thanks, closing
